// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunisiaEco.Data;

#nullable disable

namespace TunisiaEco.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203194440_AddMoreDestinations")]
    partial class AddMoreDestinations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TunisiaEco.Core.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Guided tour to observe migratory birds with expert ornithologist",
                            DestinationId = 1,
                            Difficulty = 0,
                            DurationHours = 4,
                            Name = "Bird Watching Tour",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn landscape and wildlife photography techniques",
                            DestinationId = 1,
                            Difficulty = 0,
                            DurationHours = 3,
                            Name = "Nature Photography Workshop",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Guided hike through Mediterranean forest trails to Roman aqueducts",
                            DestinationId = 2,
                            Difficulty = 1,
                            DurationHours = 5,
                            Name = "Mountain Hiking Adventure",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Discover ancient Roman water systems and ruins",
                            DestinationId = 2,
                            Difficulty = 0,
                            DurationHours = 3,
                            Name = "Archaeological Exploration",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Natural hot spring bathing with therapeutic benefits",
                            DestinationId = 3,
                            Difficulty = 0,
                            DurationHours = 2,
                            Name = "Thermal Bath Experience",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Scenic hike along Mediterranean cliffs",
                            DestinationId = 3,
                            Difficulty = 1,
                            DurationHours = 4,
                            Name = "Coastal Cliff Hiking",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Kayak along pristine coastline with marine life observation",
                            DestinationId = 4,
                            Difficulty = 1,
                            DurationHours = 3,
                            Name = "Sea Kayaking Adventure",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Learn traditional Tunisian fishing methods with local fishermen",
                            DestinationId = 4,
                            Difficulty = 0,
                            DurationHours = 4,
                            Name = "Traditional Fishing Experience",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "4x4 tour to observe desert wildlife including oryx and gazelles",
                            DestinationId = 5,
                            Difficulty = 1,
                            DurationHours = 6,
                            Name = "Desert Safari",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Stargazing in the Sahara with astronomer guide",
                            DestinationId = 5,
                            Difficulty = 0,
                            DurationHours = 2,
                            Name = "Desert Night Sky Observation",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Explore marine biodiversity in protected waters",
                            DestinationId = 6,
                            Difficulty = 0,
                            DurationHours = 3,
                            Name = "Snorkeling Expedition",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Boat tour to observe rare seabird colonies",
                            DestinationId = 6,
                            Difficulty = 0,
                            DurationHours = 4,
                            Name = "Seabird Watching",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Suspended walkway through cork oak forest canopy",
                            DestinationId = 7,
                            Difficulty = 1,
                            DurationHours = 3,
                            Name = "Forest Canopy Walk",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Guided mountain bike trails through pine forests",
                            DestinationId = 7,
                            Difficulty = 2,
                            DurationHours = 4,
                            Name = "Mountain Biking",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Evening tour to experience spectacular sunset colors on salt lake",
                            DestinationId = 8,
                            Difficulty = 0,
                            DurationHours = 2,
                            Name = "Salt Lake Sunset Tour",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Professional photography tour capturing desert landscapes",
                            DestinationId = 8,
                            Difficulty = 1,
                            DurationHours = 5,
                            Name = "Desert Photography Expedition",
                            Price = 60.00m
                        });
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BestSeason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestSeason = "Winter (November-March)",
                            Category = 0,
                            ConservationStatus = 1,
                            Description = "UNESCO Biosphere Reserve and World Heritage site known for its lakes and migratory birds including flamingos, storks, and ducks. One of the last remaining freshwater lakes in North Africa.",
                            ImageUrl = "/images/ichkeul.jpg",
                            Latitude = 37.1625m,
                            Longitude = 9.6647m,
                            Name = "Ichkeul National Park",
                            Region = "Bizerte"
                        },
                        new
                        {
                            Id = 2,
                            BestSeason = "Spring (March-May)",
                            Category = 5,
                            ConservationStatus = 0,
                            Description = "Mountain reserve with Roman aqueducts, diverse Mediterranean flora, and hiking trails offering panoramic views. Known as the 'Water Castle' for its springs that supplied ancient Carthage.",
                            ImageUrl = "/images/zaghouan.jpg",
                            Latitude = 36.4028m,
                            Longitude = 10.1425m,
                            Name = "Djebel Zaghouan",
                            Region = "Zaghouan"
                        },
                        new
                        {
                            Id = 3,
                            BestSeason = "All Year",
                            Category = 3,
                            ConservationStatus = 1,
                            Description = "Natural hot springs by the Mediterranean sea, known for therapeutic properties since Roman times. Stunning coastal cliffs and hiking paths.",
                            ImageUrl = "/images/korbous.jpg",
                            Latitude = 36.8167m,
                            Longitude = 10.5667m,
                            Name = "Korbous Thermal Springs",
                            Region = "Nabeul"
                        },
                        new
                        {
                            Id = 4,
                            BestSeason = "Spring & Autumn",
                            Category = 2,
                            ConservationStatus = 0,
                            Description = "Coastal paradise with pristine beaches, fishing villages, and citrus groves. Ideal for bird watching and coastal hikes.",
                            ImageUrl = "/images/capbon.jpg",
                            Latitude = 36.7667m,
                            Longitude = 10.8333m,
                            Name = "Cap Bon Peninsula",
                            Region = "Nabeul"
                        },
                        new
                        {
                            Id = 5,
                            BestSeason = "Winter (October-March)",
                            Category = 4,
                            ConservationStatus = 2,
                            Description = "Desert park protecting the last populations of scimitar-horned oryx and dorcas gazelle. Saharan ecosystem with rare desert flora.",
                            ImageUrl = "/images/siditoui.jpg",
                            Latitude = 32.6833m,
                            Longitude = 10.5000m,
                            Name = "Sidi Toui National Park",
                            Region = "Tataouine"
                        },
                        new
                        {
                            Id = 6,
                            BestSeason = "Summer (June-September)",
                            Category = 2,
                            ConservationStatus = 1,
                            Description = "Marine protected area and UNESCO Biosphere Reserve. Steep cliffs, crystal clear waters, and important seabird colonies including Cory's shearwaters.",
                            ImageUrl = "/images/zembra.jpg",
                            Latitude = 37.1333m,
                            Longitude = 10.8000m,
                            Name = "Zembra Island",
                            Region = "Nabeul"
                        },
                        new
                        {
                            Id = 7,
                            BestSeason = "Summer (June-September)",
                            Category = 5,
                            ConservationStatus = 0,
                            Description = "Cork oak and pine forests in Tunisia's highest mountains. Known as 'Little Switzerland' for its cool climate and hiking trails.",
                            ImageUrl = "/images/aindraham.jpg",
                            Latitude = 36.7750m,
                            Longitude = 8.6922m,
                            Name = "Ain Draham Forest",
                            Region = "Jendouba"
                        },
                        new
                        {
                            Id = 8,
                            BestSeason = "Winter (November-February)",
                            Category = 4,
                            ConservationStatus = 3,
                            Description = "Vast salt lake in the Sahara desert, famous for its mirages and unique salt formations. Best visited at sunset for spectacular colors.",
                            ImageUrl = "/images/chott.jpg",
                            Latitude = 33.7000m,
                            Longitude = 8.4000m,
                            Name = "Chott El Jerid",
                            Region = "Tozeur"
                        });
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Activity", b =>
                {
                    b.HasOne("TunisiaEco.Core.Models.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Destination", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
