// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunisiaEco.Data;

#nullable disable

namespace TunisiaEco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TunisiaEco.Core.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Observe migratory birds including flamingos and ducks",
                            DestinationId = 1,
                            Difficulty = 0,
                            DurationHours = 3,
                            Name = "Bird Watching",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Guided hike through Mediterranean forest trails",
                            DestinationId = 2,
                            Difficulty = 1,
                            DurationHours = 4,
                            Name = "Mountain Hiking",
                            Price = 40.00m
                        });
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BestSeason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestSeason = "Winter",
                            Category = 0,
                            ConservationStatus = 1,
                            Description = "UNESCO Biosphere Reserve known for its lakes and migratory birds",
                            ImageUrl = "/images/ichkeul.jpg",
                            Latitude = 37.1625m,
                            Longitude = 9.6647m,
                            Name = "Ichkeul National Park",
                            Region = "Bizerte"
                        },
                        new
                        {
                            Id = 2,
                            BestSeason = "Spring",
                            Category = 5,
                            ConservationStatus = 0,
                            Description = "Mountain reserve with Roman aqueducts and diverse flora",
                            ImageUrl = "/images/zaghouan.jpg",
                            Latitude = 36.4028m,
                            Longitude = 10.1425m,
                            Name = "Djebel Zaghouan",
                            Region = "Zaghouan"
                        });
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Activity", b =>
                {
                    b.HasOne("TunisiaEco.Core.Models.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TunisiaEco.Core.Models.Destination", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
